### ISSUE TITLE
Error on fetching data from server

### ISSUE THREAD

**Issue by do1osc** [schmupu/ioBroker.pollenflug#10]
Where:
Version 1.0.3

What:
On fetching data from dwd-server i get this errors in iobroker.log:

pollenflug.0 | 2019-10-19 11:54:39.415 | error | (7966) Error reading pollen risk index.
-- | -- | -- | --
pollenflug.0 | 2019-10-19 11:54:39.414 | error | (7966) Error requesting URL https://opendata.dwd.de/climate_environment/health/alerts/s31fg.json

With browser it is possible to get the data.
With "wget" i get the following error:

Verbindungsaufbau zu opendata.dwd.de (opendata.dwd.de)|141.38.2.22|:443 … verbunden.
FEHLER: Dem Zertifikat von »opendata.dwd.de« wird nicht vertraut.
FEHLER: Das Zertifikat von »»opendata.dwd.de«« wurde von einem unbekannten Austeller herausgegeben.

**Comment by schmupu** [comment]
Problem fixed in Version 1.0.4. If you use the latest version in ioBroker. If you use the stable versions, you have to wait a few days or load the version from GitHub in ioBroker.

**Comment by do1osc** [comment]
Ok, 1.0.4 is working..
