### ISSUE TITLE
Your english is not the yellow from the egg :-D

### ISSUE THREAD

**Issue by ldittmar81** [schmupu/ioBroker.pollenflug#2]
https://github.com/schmupu/ioBroker.pollenflug/blob/82ba28f7e78af53da629881dd0f81823c7d0be73/io-package.json#L17

Nee... da hast du nur vertauscht. Und wenn wir schon dabei sind: schon mal die automatische Übersetzung ausprobiert? https://forum.iobroker.net/topic/19047/gulp-ist-kein-hexenwerk-auto-translation

**Comment by schmupu** [comment]
Da will man ganz heimlich ein Adapter entwickeln 😀 
Danke für den Tipp, ich werde die Sprache anpassen
