### ISSUE TITLE
warnings with Version 0.1.2

### ISSUE THREAD

**Issue by Seqway** [schmupu/ioBroker.pollenflug#3]
I installed the adapter and it is running but many warnings are in the LOG:

Here directly in the javascript log:

>14:46:55.498 | info | javascript.0 Stop script script.js.UserDefined.Tests.Pollenvorhersage-- | -- | --
>14:46:58.086 | info | javascript.0 script.js.UserDefined.Tests.Pollenvorhersage: compiling TypeScript source...
>14:46:58.087 | info | javascript.0 script.js.UserDefined.Tests.Pollenvorhersage: TypeScript compilation successful
>14:46:58.087 | info | javascript.0 script.js.UserDefined.Tests.Pollenvorhersage: registered 0 subscriptions and 1 schedule
>14:46:58.700 | warn | javascript.0     at Request._callback script.js.UserDefined.Tests.Pollenvorhersage:275:21)
>14:46:58.701 | warn | javascript.0     at Request._callback (script.js.UserDefined.Tests.Pollenvorhersage:275:21)
>14:46:58.703 | warn | javascript.0     at Request._callback (script.js.UserDefined.Tests.Pollenvorhersage:275:21)

Here in the normal logfile:

>javascript.0 | 2019-02-22 14:46:58.905 | warn | at process._tickCallback (internal/process/next_tick.js:63:19)
-- | -- | -- | --
>javascript.0 | 2019-02-22 14:46:58.905 | warn | at endReadableNT (_stream_readable.js:1103:12)
>javascript.0 | 2019-02-22 14:46:58.905 | warn | at IncomingMessage.emit (events.js:194:15)
>javascript.0 | 2019-02-22 14:46:58.905 | warn | at Object.onceWrapper (events.js:277:13)
>javascript.0 | 2019-02-22 14:46:58.905 | warn | at IncomingMessage.<anonymous>  (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:1083:12)
>javascript.0 | 2019-02-22 14:46:58.905 | warn | at Request.emit (events.js:189:13)
>javascript.0 | 2019-02-22 14:46:58.904 | warn | at Request.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:1161:10)
>javascript.0 | 2019-02-22 14:46:58.904 | warn | at Request.emit (events.js:189:13)
>javascript.0 | 2019-02-22 14:46:58.904 | warn | at Request.self.callback (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:185:22)
>javascript.0 | 2019-02-22 14:46:58.904 | warn | at Request._callback (script.js.UserDefined.Tests.Pollenvorhersage:275:21)
>javascript.0 | 2019-02-22 14:46:58.904 | warn | at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1255:20)
>javascript.0 | 2019-02-22 14:46:58.903 | warn | Wrong type of >javascript.0.wetter.pollenvorhersage.d1.beifuss:  "undefined". Please fix, while deprecated and will not work in next  versions.

**Comment by schmupu** [comment]
Da werde ich Dir nicht weiterhelfen können. Das Script Pollenvorhersage ist nicht von mir. Das ist unabhängig vom Adapter pollenflug
