### ISSUE TITLE
Transfer adapter to community adapters

### ISSUE THREAD

**Issue by klein0r** [schmupu/ioBroker.pollenflug#44]
see https://github.com/iobroker-community-adapters/info#add-git-repo-to-organization

**Comment by klein0r** [comment]
@mcm1957 Can you do that?

**Comment by mcm1957** [comment]
Yes i can do it
Will last until end of week due to hilydays.

What about the original deb? Has he confirmrd or is he / she at least infomed 

Edit
Just sawthat issue is 1 year old. Should have been enogh time to react.

**Comment by mcm1957** [comment]
@klein0r 
2.0.0 should be available at latest tomorrow.

Feel free to test / fix / modify the adapter.
